<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\CuisineController::creerAliment' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\CuisineController::creerBoite' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\CuisineController::creerProduit' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\CuisineController::creerRecette' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\CuisineController::creerStockage' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\CuisineController::creerTypeAliment' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\CuisineController::listingAliments' => function () {
    return ($this->privates['.service_locator.QNjy4qW'] ?? $this->load('get_ServiceLocator_QNjy4qWService.php'));
}, 'App\\Controller\\CuisineController::listingBoites' => function () {
    return ($this->privates['.service_locator.D.JiliE'] ?? $this->load('get_ServiceLocator_D_JiliEService.php'));
}, 'App\\Controller\\CuisineController::listingProduit' => function () {
    return ($this->privates['.service_locator.Uzpehyh'] ?? $this->load('get_ServiceLocator_UzpehyhService.php'));
}, 'App\\Controller\\CuisineController::listingStockage' => function () {
    return ($this->privates['.service_locator.qGKb5kz'] ?? $this->load('get_ServiceLocator_QGKb5kzService.php'));
}, 'App\\Controller\\CuisineController::listingTypesAliment' => function () {
    return ($this->privates['.service_locator.W9fDenB'] ?? $this->load('get_ServiceLocator_W9fDenBService.php'));
}, 'App\\Controller\\CuisineController::remplirBoite' => function () {
    return ($this->privates['.service_locator.gY3.SUg'] ?? $this->load('get_ServiceLocator_GY3_SUgService.php'));
}, 'App\\Controller\\CuisineController:creerAliment' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\CuisineController:creerBoite' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\CuisineController:creerProduit' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\CuisineController:creerRecette' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\CuisineController:creerStockage' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\CuisineController:creerTypeAliment' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\CuisineController:listingAliments' => function () {
    return ($this->privates['.service_locator.QNjy4qW'] ?? $this->load('get_ServiceLocator_QNjy4qWService.php'));
}, 'App\\Controller\\CuisineController:listingBoites' => function () {
    return ($this->privates['.service_locator.D.JiliE'] ?? $this->load('get_ServiceLocator_D_JiliEService.php'));
}, 'App\\Controller\\CuisineController:listingProduit' => function () {
    return ($this->privates['.service_locator.Uzpehyh'] ?? $this->load('get_ServiceLocator_UzpehyhService.php'));
}, 'App\\Controller\\CuisineController:listingStockage' => function () {
    return ($this->privates['.service_locator.qGKb5kz'] ?? $this->load('get_ServiceLocator_QGKb5kzService.php'));
}, 'App\\Controller\\CuisineController:listingTypesAliment' => function () {
    return ($this->privates['.service_locator.W9fDenB'] ?? $this->load('get_ServiceLocator_W9fDenBService.php'));
}, 'App\\Controller\\CuisineController:remplirBoite' => function () {
    return ($this->privates['.service_locator.gY3.SUg'] ?? $this->load('get_ServiceLocator_GY3_SUgService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
