<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qGKb5kz' shared service.

return $this->privates['.service_locator.qGKb5kz'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('repo' => function (): \App\Repository\StockageRepository {
    return ($this->privates['App\Repository\StockageRepository'] ?? $this->load('getStockageRepositoryService.php'));
}));
