<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.gY3.SUg' shared service.

return $this->privates['.service_locator.gY3.SUg'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('boite' => function (): \App\Entity\Boite {
    return ($this->privates['.errored..service_locator.gY3.SUg.App\Entity\Boite'] ?? $this->load('getBoiteService.php'));
}, 'manager' => function () {
    return ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));
}));
