<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Uzpehyh' shared service.

return $this->privates['.service_locator.Uzpehyh'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('repo' => function (): \App\Repository\ProduitRepository {
    return ($this->privates['App\Repository\ProduitRepository'] ?? $this->load('getProduitRepositoryService.php'));
}));
