<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.QNjy4qW' shared service.

return $this->privates['.service_locator.QNjy4qW'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('repo' => function (): \App\Repository\AlimentRepository {
    return ($this->privates['App\Repository\AlimentRepository'] ?? $this->load('getAlimentRepositoryService.php'));
}));
