<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUvzBA6Z\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUvzBA6Z/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUvzBA6Z.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUvzBA6Z\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUvzBA6Z\srcDevDebugProjectContainer([
    'container.build_hash' => 'UvzBA6Z',
    'container.build_id' => '1a98a193',
    'container.build_time' => 1552998351,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUvzBA6Z');
