<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerStcWIGv\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerStcWIGv/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerStcWIGv.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerStcWIGv\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerStcWIGv\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'StcWIGv',
    'container.build_id' => 'ffd146a8',
    'container.build_time' => 1552134788,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerStcWIGv');
