<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAg0raKo\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAg0raKo/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAg0raKo.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAg0raKo\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerAg0raKo\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ag0raKo',
    'container.build_id' => '04a77dfb',
    'container.build_time' => 1544184191,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAg0raKo');
